version: 1

labels:
  - label: 'bug'
    title: '(?i)\[?bug[:\]]'

  - label: 'feature'
    title: '(?i)\[?(feature|feat)[:\]]'

  - label: '1.20'
    title: '\[?1\.20(\.\d+|\.x)?[:\]]?'

  - label: 'triage'
    title: '.*'
    mergeable: false
