name: Release Arc

on:
  push:
    tags:
      - '*'

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    name: Build and Release Arc
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set-Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: x64
          cache: 'gradle'

      - name: Read Gradle Properties
        uses: BrycensRanch/read-properties-action@v1.0.4
        id: all
        with:
          file: gradle.properties
          all: true

      - name: Build Arc
        run: ./gradlew build

      - name: Publish release to maven
        id: upload
        run: ./gradlew publish -PmavenType=release -PmavenUsername=${{ secrets.MAVEN_USER }} -PmavenPassword=${{ secrets.MAVEN_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: Arc ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          append_body: true
          make_latest: "true"
          files: |
            build/libs/arc-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}.jar
